import { z } from "zod/v4";

export const userSchema = z.object({
  // id will be generated by crypto.randomUUID()
  id: z.uuidv4(),
  label: z.string(),
  email: z.email(),
  password_hash_b64: z.base64(),
  password_salt: z.string(),
});

export type User = z.infer<typeof userSchema>;
